### ISSUE TITLE
Error if reloader: true

### ISSUE THREAD

**Issue by louismerlin** [Fnux/sinatra-blog#1]
When `reloader: true`, I get this on `rackup`
>[Sinatra Blog]
>/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- sinatra/reloader (LoadError)
>	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
>	from /home/louis/Code/sinatra-blog/config.ru:14:in `block in <main>'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
>	from /home/louis/Code/sinatra-blog/config.ru:in `new'
>	from /home/louis/Code/sinatra-blog/config.ru:in `<main>'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
>	from /home/louis/.gem/ruby/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
>	from /home/louis/.gem/ruby/2.2.0/bin/rackup:23:in `load'
>	from /home/louis/.gem/ruby/2.2.0/bin/rackup:23:in `<main>'

**Comment by Fnux** [comment]
`sinatra-reloader` is part of the [sinatra-contrib](http://www.sinatrarb.com/contrib/) gem.
> Starting with 1.3.0, every Sinatra release will be followed by a Sinatra::Contrib release which will include collection of common Sinatra extensions.


```
gem install sinatra-contrib
```
